language: go

go:
 - 1.6.2

install:
 - export GOPATH="${TRAVIS_BUILD_DIR}:$GOPATH"
 - go get -u github.com/cihub/seelog
 - go get -u github.com/dropbox/dropbox-sdk-go-unofficial
 - go get -u google.golang.org/api/admin/directory/v1
 - go get -u google.golang.org/cloud/compute/metadata

script:
 - go test -v ./test/github.com/watermint/dcfg

